language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.1
    - android-23

jdk:
  - oraclejdk8

before_install:
  - env
  - nvm install 6
  - nvm use 6
install:
  - npm i
script:
  - jarsigner -verify -verbose -certs test/android-release-unsigned.apk | grep "unsigned"
  - ls /usr/local/android-sdk/build-tools/
  
  - PATH=$PATH:/usr/local/android-sdk/build-tools/23.0.1/ ./apk-signer -f test/android-release-unsigned.apk -a foobar -k test/foobar.keystore -s foobar
  
  - stat test/android-release-unaligned.apk
  - stat test/android-release.apk
  
  - jarsigner -verify -verbose -certs test/android-release-unaligned.apk
  - jarsigner -verify -verbose -certs test/android-release-unaligned.apk | grep -m 1 Foobar

  - jarsigner -verify -verbose -certs test/android-release.apk
  - jarsigner -verify -verbose -certs test/android-release.apk | grep -m 1 Foobar